---
- sysctl:
    name: "{{item.key}}"
    value: "{{item.value}}"
    state: present
    reload: yes
  loop: "{{es_sysctls|dict2items}}"
  tags: [sysctl]
- name: Create directories
  file:
    path: "{{es_versioned_hostdir}}/{{ item.path }}"
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: "{{playbook_dir}}/setup/"
  when: item.state == 'directory'
- name: Template files
  template:
    src: '{{ item.src }}'
    dest: "{{es_versioned_hostdir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
    trim_blocks: false
  with_filetree: "{{playbook_dir}}/setup/"
  when:
  - "item.state == 'file'"
  - "not item.path|regex_search('\\.frep$|conf.d|maintenance.*\\.py')"
- name: Copy files
  copy:
    src: '{{ item.src }}'
    dest: "{{es_versioned_hostdir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
  with_filetree: "{{playbook_dir}}/setup/"
  when:
  - "item.state == 'file'"
  - "     item.path|regex_search('\\.frep$|conf.d|maintenance.*\\.py')"
- name: Synchronise scripts
  delegate_to: "localhost"
  synchronize:
    compress: false
    ssh_args: "{{es_sshargs}}"
    src: "./scripts/"
    dest: "{{es_hostdir}}/scripts/"
    rsync_opts: "{{es_code_rsync_opts}}"
    set_remote_user: "no"
  tags: [sync_scripts]
